#é…ç½®æ•°æ®æº?
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/trail?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: rootroot
      max-active: 20
      max-wait: 5000
      initial-size: 1
      filters: stat,log4j,wall
      validation-query: SELECT 'X'   #éªŒè¯è¿æ¥
      enable: true
    #ç›‘æ§é…ç½®
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
        url-pattern: /druid/*

  servlet:
      multipart:
        max-file-size: 1MB
        max-request-size: 10MB

  #thymeleafçš„é…ç½?
  thymeleaf:
    cache: false
    enabled: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#é…ç½®mybatisplus
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#shiroçš„é…ç½?
shiro:
  hash-algorithm-name: md5
  hash-iterations: 2
  anon-urls:
  - /index.html*
  - /sys/toLogin*
  - /login/login*
  - /login/getCode
  - /resources/**
  login-url: /index.html
  log-out-url: /login/logout*
  authc-ulrs:
  - /**

#ä¿®æ”¹ç«¯å£å·ä¸º8088
server:
  port: 8888


